spring.application.name=book-tracker

spring.datasource.url=jdbc:postgresql://localhost:5434/book_tracker_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

api.security.token.secret=12345678